name: musicplayer
description: Music Player.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.15.1
  cupertino_icons: ^0.1.3
  flutter_audio_query: ^0.3.4+2
  flutter_bloc: ^3.2.0
  marquee: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
